platform :ios, '15.0'
$FirebaseSDKVersion = '10.25.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods',
  :deterministic_uuids => false,
  :warn_for_multiple_pod_sources => false

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/bidon-io/CocoaPods-Specs.git'
source 'https://cdn.cocoapods.org'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Run flutter pub get first"
  end
  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def appodeal
    pod 'Appodeal', '4.2.0'
    # Core adapters
    pod 'AppodealGoogleAdMobAdapter', '12.13.0.0'
    pod 'AppodealFacebookAdapter', '18.0.1.0'
    pod 'AppodealAppLovinAdapter', '13.5.1.0'
    pod 'AppodealMintegralAdapter', '7.7.9.0'
    pod 'AppodealVungleAdapter', '7.6.2.0'
    pod 'AppodealUnityAdapter', '4.16.3.0'
    pod 'AppodealInMobiAdapter', '11.1.0.0'
    pod 'AppodealIronSourceAdapter', '9.1.0.0.0'
    pod 'AppodealMyTargetAdapter', '5.36.2.0'
    pod 'AppodealBigoAdsAdapter', '5.0.0.0'
    pod 'AppodealSmaatoAdapter', '23.1.0.0'
    pod 'AppodealYandexAdapter', '7.17.0.1'
    pod 'AppodealChartboostAdapter', '9.10.1.0'
    pod 'AppodealFyberAdapter', '8.4.1.0'
    pod 'AppodealAmazonAdapter', '5.3.2.0'
    pod 'AppodealBidMachineAdapter', '3.7.1.0'
    pod 'AppodealBidonAdapter', '0.15.0.0'
    pod 'AppodealDTExchangeAdapter', '8.4.1.0'
end

target 'Runner' do
  use_frameworks!
  appodeal
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.9'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'HAVE_AV_CONFIG_H=1']
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
